### PR TITLE
Bouncy ball simulation

### PR DESCRIPTION
**Pull request by liamf**
Hi

an animation which probably fits either between the current 2 and 3, or after 3.

It is a simple bouncing ball simulation: uses a ball image, shows a function called on keypress, finding an element in the document by name, a simple class in CSS.

It looks more like a "real" bouncing ball then the dojo logo.

Whaddya think?

### CODE REVIEW

**Comment by No9** [comment]
Loving that!! 
Its a really good continuation of animation2.
The comments in the code are spot on as well without being to verbose.
I noticed my stuff was very lacking in that area 

Is there a reason why you moved the onkeypress event back into the HTML and ditched the setup that called animate() like we did in animation2?

I was trying to get away from dirtying the HTML with javascript code and if we want to move on to more gamey things they are going to have to get used to adding images / events dynamically to the page as we did in animation2.html

I think we should try to keep it consistent. 
If you have time can you make the tweeks? If not I will see if I can patch it before Saturday but it would be great to deliver this at the next dojo. 

Thanks Again.

**Comment by liamf** [comment]
Good comments, I will update. No particular reason to have onkeypress back in the HTML, just did it that way when throwing it together.

I will move the  tiny CSS fragment into a separate file and move the image into the images dir too.

It also slightly offends my inner nerd that the bouncing is not physics-compliant ... may try and fix that, although my first attempt did not look right.

If I get some time I will also write up some "cards" like James proposed for animation2.

**Comment by liamf** [comment]
OK, I made some updates to the code.
- made a CSS directory, and moved the CSS into that (and style.css too, and updated animationX files)
- moved all javascript into the bouncy.js file, added a setup fn
- construct the <div> and  in the javascript, so like animation2
- fixed up some comments

I looked into making it "Newton compliant" by having the ball bounce "properly" (i.e. s = ut + (at**2)/2) but that adds considerable mathematical complexity to the position and bounce calculation to make it work properly and does not really add to the example, so dropped it.

**Comment by liamf** [comment]
There are also some deliberate shortcomings in the code, to help with teaching.

For example, you can set the size of the ball with CSS. But if you pick anything other than "medium" it will not bounce on the edge of the window. If you don't set the size to be medium, it won't bounce on the edge either, since the native image is not 50x50. 

Does not handle window resizing

If you make "bouncy" > 1, it will do peculiar things.

I would probably do this in stages: first leave out the onkeypress, ball bounces forever. Then add it in: oh look, you can make it slow down. Then handle the keypress: oh look, different stuff can happen depending on key, etc etc.

HTH

Liam

**Comment by No9** [comment]
# wOOT!

Do you fancy delivering it this saturday?

**Comment by liamf** [comment]
That would be cool, but unfortunately I promised the kids I'd take them down the country to see their cousins this w/e

Another time I will definitely come in and help out. Only fair: Eugene and James have already or will shortly help out in UCD.

**Comment by liamf** [comment]
Oh and one more tweak added to my fork: if you're interested I will add a pull request for that.

Added to the images dir an animated gif of the ball, plus one frame from that animation as a .jpg. If you use that in place of the "football.gif" image, then it bounces and spins. Spiffy.

But then, when it stops bouncing, it keeps spinning of course ... which looks odd.

So an exercise for the student is to make is stop spinning when it stops bouncing: by replacing the ball image with the non-animated frame.

Now I really should get back to the day job.

**Comment by No9** [comment]
Yup put it in. The more the merrier.

**Pull request merged**
